### ISSUE TITLE
Clarifying Button Label "Board is adding books" and Loading Status on Book Search Page

### ISSUE THREAD

**Issue by inkerton** [ELEVATE-Project/project-frontend#2]
This label "board is adding books" is misleading as it implies a content loading process, while it actually functions as a hyperlink to another page. I suggest relabeling it as "Explore content" to accurately reflect its purpose and avoid user confusion.

When searching books for CBSE, NCERT, and States/UTs, there comes this button which leads the user to thinking its loading and going to show content. I personally waited for around 15-20 minutes thinking the content is still loading.

![Screenshot 2023-05-22 225332](https://github.com/ELEVATE-Project/project-frontend/assets/127668005/43c0f77f-a4cc-424e-9607-c01d8d785f07)

**Comment by shashwatm1111** [comment]
Hey @inkerton , I would really like to work upon this issue , kindly assign me this under C4GT .

**Comment by kiranharidas187** [comment]
Hi @inkerton ,

This issue is not related to project flow hence closing the issue
