### ISSUE TITLE
Problem with Subject Filter on Book Search Page

### ISSUE THREAD

**Issue by inkerton** [ELEVATE-Project/project-frontend#3]
The subject filter option does not appear to be functioning correctly, hindering users' ability to refine their search results based on specific subjects. This limitation significantly impacts the usability and effectiveness of the book search feature. I kindly request your attention to investigate and resolve this matter to provide a seamless user experience.

Link: [https://diksha.gov.in/nios/explore?board=State%20(Delhi)&medium=English&gradeLevel=Others&&id=dl_k-12_1&selectedTab=textbook](url)

![Screenshot 2023-05-22 230129](https://github.com/ELEVATE-Project/project-frontend/assets/127668005/17374e28-f5b2-4100-8e95-39a9f22b77e1)

**Comment by hetvi-45** [comment]
I would like to take up this issue. I have good knowledge of all the tech stack like angular, nodejs, ionic, html and css so please assign this issue to me.

**Comment by kiranharidas187** [comment]
Hi @hetvi-45 

This issue is not related to project flow hence closing the issue
